Add validation to import script
And handle passing in extra V

diff --git a/scripts/import-spec b/scripts/import-spec
--- a/scripts/import-spec
+++ b/scripts/import-spec
@@ -2,8 +2,13 @@
 
 set -eu
 
-version="$1"; shift
+version="${1#V}"; shift
 date="$1"; shift
+
+if ! [ -d "res/specifications/VocaLink-V${version}" ]; then
+    echo "Cannot find specification in res/specifications/VocaLink-V${version}!" >&2
+    exit 1
+fi
 
 cp tests/Spec/VocaLinkV460.fixtures.txt tests/Spec/VocaLinkV${version}.fixtures.txt
 cat tests/Spec/VocaLinkV460Test.php \
